import icaro.infraestructura.recursosOrganizacion.recursoTrazas.ItfUsoRecursoTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.*;
import icaro.infraestructura.patronAgenteCognitivo.procesadorObjetivos.gestorTareas.ItfGestorTareas;
import icaro.infraestructura.entidadesBasicas.PerformativaUsuario;
import icaro.infraestructura.entidadesBasicas.comunicacion.*
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoMedico.objetivos.*;
import icaro.aplicaciones.informacion.gestionCitas.*;
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoMedico.tareas.*;
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoMedico.tools.*;
import static icaro.aplicaciones.recursos.recursoCalendario.imp.RecursoCalendarioImp.*;
import static icaro.aplicaciones.recursos.persistenciaUsuarios.imp.PersistenciaUsuariosImp.*;

global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;

rule "crear foco usuario"
 when 
 	notif:NotificacionMedico(identInterlc:identNotificador)
 	not( exists( FocoUsuario(usuario == identInterlc ) ))
 then
 	//Establezco el foco del usuario
 	FocoUsuario fu = new FocoUsuario(identInterlc);
 	insert(fu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
end

rule "Inicio obtención datos anulacion cita"
 when
    notif:NotificacionMedico(identInterlc:identNotificador, tipoNotificacion == tipoNotifMedico.inicioAnulacion);
    fu:FocoUsuario(usuario == identInterlc);
 then
 	Tarea tareadist = gestorTareas.crearTarea(NotificarObjetivo.class);
    tareadist.ejecutar(identInterlc,notif,"MEDICO"); 	
 
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(identInterlc,conversacionMedico.obtenerInfoAnulacion);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
    
    retract(notif);
    
    Objetivo anularCitas = new AnularCitas();
    anularCitas.setobjectReferenceId(identInterlc);
 	insert(anularCitas);
    
    Objetivo idFechaInicio = new IdentificarFechaInicio();
 	idFechaInicio.setobjectReferenceId(identInterlc);
 	insert(idFechaInicio);
 	
 	// Objetivo idFechaFin = new IdentificarFechaFin();
 	// idFechaFin.setobjectReferenceId(identInterlc);
 	// insert(idFechaFin);
 	
 	fu.setFoco(anularCitas);
 	update(fu);
 	
end


rule "Obtencion de la fecha inicio sin tener la fecha fin"
 when
    notif:NotificacionMedico(identInterlc:identNotificador, tipoNotificacion == tipoNotifMedico.fechaInicio, msgg:mensajeNotificacion )
    fechaIni:IdentificarFechaInicio(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    obj:AnularCitas(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    fu:FocoUsuario(usuario == identInterlc, foco == obj)
 then
 	fechaIni.setSolved();
 	
 	obj.setFechaInicio(msgg);
 	
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(identInterlc,conversacionMedico.obtenerFechaInicioOK);
    tarea.ejecutar(identInterlc,conversacionMedico.obtenerFechaFin);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
 	
 	update(fechaIni);
    retract(notif);
end

rule "Obtencion de la fecha fin sin tener la fecha inicio"
 when
    notif:NotificacionMedico(identInterlc:identNotificador, tipoNotificacion == tipoNotifMedico.fechaFin, msgg:mensajeNotificacion )
    fechaFin:IdentificarFechaFin(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    obj:AnularCitas(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    fu:FocoUsuario(usuario == identInterlc, foco == obj)
 then
 	fechaFin.setSolved();
 	
 	obj.setFechaFin(msgg);
 	
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(identInterlc,conversacionMedico.obtenerFechaFinOK);
    tarea.ejecutar(identInterlc,conversacionMedico.obtenerFechaInicio);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
 	
 	update(fechaFin);
    retract(notif);
end

rule "Focalizar anular cita"
 when
    fechaIni:IdentificarFechaInicio(state == Objetivo.SOLVED, identInterlc:objectReferenceId) 
    // fechaFin:IdentificarFechaFin(state == Objetivo.SOLVED, objectReferenceId == identInterlc)
    obj:AnularCitas(state == Objetivo.PENDING, objectReferenceId == identInterlc)
 then
    obj.setSolving();
    
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(identInterlc,conversacionMedico.validarAnulacionCitas1 + obj.getFechaInicio() + conversacionMedico.validarAnulacionCitas3);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
 	
 	retract(fechaIni);
 	// retract(fechaFin);
 	
 	update(obj);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
end

rule "Validar anulacion de citas"
 when
 	notif:NotificacionMedico(identInterlc:identNotificador, tipoNotificacion == tipoNotifMedico.si, msgg:mensajeNotificacion )
    obj:AnularCitas(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
 then
 	Objetivo validar = new ValidarAnular();
 	validar.setobjectReferenceId(identInterlc);
 	validar.setSolving();
 	insert(validar);
 	
    retract(notif);

    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
end

rule "No validar anulacion de citas"
 when
 	notif:NotificacionMedico(identInterlc:identNotificador, tipoNotificacion == tipoNotifMedico.no, msgg:mensajeNotificacion )
    obj:AnularCitas(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
 then
 	
    retract(notif);
 	
 	Tarea tareadist2 = gestorTareas.crearTarea(NotificarObjetivo.class);
    tareadist2.ejecutar(identInterlc,null,"RESET"); 

    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
end


rule "Anulacion confirmada"
 when
 	anular:AnularCitas(state == Objetivo.SOLVING, identInterlc:objectReferenceId)
    validar:ValidarAnular(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
	fu:FocoUsuario(usuario == identInterlc, foco == anular)
 then
 	String fechaI = anular.getFechaInicio();
    //String fechaF = anular.getFechaFin();
 	Tarea tareadist2 = gestorTareas.crearTarea(NotificarObjetivo.class);
    tareadist2.ejecutar(identInterlc,null,"RESET"); 
    
    // AQUI LLAMAREMOS AL RECURSO DE CANLENDARIO PARA BORRAR LAS FECHAS QUE TOQUEN Y AVISAR A LOS USUARIOS 	
    String nombremedico = getNombrePersistenciaUsuarios(identInterlc);
 	TareaSincrona tareadist = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    if(nombremedico.isEmpty()) {
    	
 		String msgToSend = conversacionMedico.errorAnulrCitas1;
    	tareadist.ejecutar(identInterlc,msgToSend); 	
    } else {
    
    	darBajaCitas(nombremedico, fechaI);
    	
 		String msgToSend = conversacionMedico.anulacionCitasCompleta1 + fechaI;
    	tareadist.ejecutar(identInterlc,msgToSend); 	
    }
 	fu.setFoco(null);
 	update(fu);
 	
 	retract(anular);
 	retract(validar);
	
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
end
