import icaro.infraestructura.recursosOrganizacion.recursoTrazas.ItfUsoRecursoTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.*;
import icaro.infraestructura.patronAgenteCognitivo.procesadorObjetivos.gestorTareas.ItfGestorTareas;
import icaro.infraestructura.entidadesBasicas.PerformativaUsuario;
import icaro.infraestructura.entidadesBasicas.comunicacion.*
import icaro.aplicaciones.agentes.AgenteAplicacionIdentificador.objetivos.*;

import icaro.aplicaciones.informacion.gestionCitas.*;

import icaro.aplicaciones.informacion.gestionQuedadas.*;
import icaro.aplicaciones.agentes.AgenteAplicacionIdentificador.tareas.*;
import icaro.aplicaciones.agentes.AgenteAplicacionIdentificador.tools.*;
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoPaciente.tools.*;
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoMedico.tools.*;
import static icaro.aplicaciones.recursos.persistenciaUsuarios.imp.PersistenciaUsuariosImp.*;

global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;


// "grupo" es el nombre del usuario del chat.

rule "Creacion de los objetivos iniciales"
when 
then 
TareaSincrona tarea = gestorTareas.crearTareaSincrona(InicializarInfoWorkMem.class);
    tarea.ejecutar();
	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
end


rule "Saludo Inicial"
when
then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(SaludoInicial.class);
     tarea.ejecutar(VocabularioGestionQuedadas.IdentRecursoComunicacionChat);
     recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Saludo inicial cuando el grupo ha saludado"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.saludo)
    not( exists (Grupo(grupo == identInterlc )))
 then
 	Grupo gr = new Grupo();
 	gr.grupo = identInterlc;
 	insert( gr );
 	FocoGrupo fgr = new FocoGrupo(identInterlc);
 	Objetivo ob = new IdentificarGrupo();
 	ob.setobjectReferenceId(identInterlc);
 	insert( fgr );
 	insert( ob );
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
    retract(notif);
end


rule "Saludo inicial cuando el grupo dice algo que no es un saludo"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion != tipoNotif.saludo)
    not( exists (Grupo(grupo == identInterlc )))
 then
 	Grupo gr = new Grupo();
 	gr.grupo = identInterlc;
 	insert( gr );
 	FocoGrupo fgr = new FocoGrupo(identInterlc);
 	Objetivo ob = new IdentificarGrupo();
 	ob.setobjectReferenceId(identInterlc);
 	insert( fgr );
 	insert( ob );
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(identInterlc,conversacion.msg("saludoInicialNoSaludo"));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
    retract(notif);
end


rule "Respuesta ante resaludo del grupo"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.saludo)
   	gr:Grupo(grupo == identInterlc)
 then
  	 TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea.ejecutar(identInterlc,conversacion.msg("volverASaludar"));
     recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
     gr.actividad();
     retract(notif);
end

rule "Regla de solicitar teléfono del grupo"
 when
 	obj:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	fc:FocoGrupo(foco == null, grupo == group)
 	not( exists (ObtenerTelefono(objectReferenceId == group)))
 then
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	Objetivo ob = new ObtenerTelefono();
  	ob.setobjectReferenceId(group);
  	fc.setFoco(ob);
  	
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(group,conversacion.msg("peticionTelefono"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	update(fc);
   	insert(ob);
end

rule "Regla de obtencion del teléfono del grupo"
 when
 	obGeneral:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerTelefono(state == Objetivo.PENDING, objectReferenceId == group)
 	fc:FocoGrupo(grupo == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.telefono, msgg:mensajeNotificacion )
    gr:Grupo(grupo == group)
 then
 	ob.setSolved();
 	gr.setTelefono(msgg);
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(group,conversacion.msg("prePersistenciaGrupo"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	update(ob);
   	update(fc);
   	retract(notif);
end

rule "Regla de solicitar sexo del grupo"
 when
 	obj:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	fc:FocoGrupo(foco == null, grupo == group)
 	not( exists (ObtenerSexo(objectReferenceId == group)))
 then
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	Objetivo ob = new ObtenerSexo();
  	ob.setobjectReferenceId(group);
  	fc.setFoco(ob);
  	
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(group,conversacion.msg("peticionSexo"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	update(fc);
   	insert(ob);
end

rule "Regla de obtencion del sexo del grupo"
 when
 	obGeneral:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerSexo(state == Objetivo.PENDING, objectReferenceId == group)
 	fc:FocoGrupo(grupo == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.sexo, msgg:mensajeNotificacion )
    gr:Grupo(grupo == group)
 then
 	ob.setSolved();
 	gr.setSexo(msgg);
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea1 = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea1.ejecutar(group, "Genial!");
    TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea2.ejecutar(group,conversacion.msg("ultimaPreguntaIdentificacion"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	update(ob);
   	update(fc);
   	retract(notif);
end

rule "Regla de solicitar edad del grupo"
 when
 	obj:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	fc:FocoGrupo(foco == null, grupo == group)
 	not( exists (ObtenerEdad(objectReferenceId == group)))
 then
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	Objetivo ob = new ObtenerEdad();
  	ob.setobjectReferenceId(group);
  	fc.setFoco(ob);
  	
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(group,conversacion.msg("peticionEdad"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	update(fc);
   	insert(ob);
end

rule "Regla de obtencion de la edad del grupo"
 when
 	obGeneral:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerEdad(state == Objetivo.PENDING, objectReferenceId == group)
 	fc:FocoGrupo(grupo == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.edad, msgg:mensajeNotificacion )
    gr:Grupo(grupo == group)
 then
 	ob.setSolved();
 	gr.setEdad(Integer.parseInt(msgg));
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(ConfirmarEdad.class);
    tarea.ejecutar(group, msgg);
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	update(ob);
   	update(fc);
   	retract(notif);
end

rule "Regla de solicitar número de integrantes del grupo"
 when
 	obj:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	fc:FocoGrupo(foco == null, grupo == group)
 	not( exists (ObtenerNumIntegrantes(objectReferenceId == group)))
 then
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	Objetivo ob = new ObtenerNumIntegrantes();
  	ob.setobjectReferenceId(group);
  	fc.setFoco(ob);
  	
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(group,conversacion.msg("peticionNumIntegrantes"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	update(fc);
   	insert(ob);
end

rule "Regla de obtencion del número de integrantes del grupo"
 when
 	obGeneral:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerNumIntegrantes(state == Objetivo.PENDING, objectReferenceId == group)
 	fc:FocoGrupo(grupo == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.numintegrantes, msgg:mensajeNotificacion )
    gr:Grupo(grupo == group)
 then
 	ob.setSolved();
 	gr.setNumIntegrantes(Integer.parseInt(msgg));
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(ConfirmarNumIntegrantes.class);
    tarea.ejecutar(group, msgg);
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	update(ob);
   	update(gr);
   	update(fc);
   	retract(notif);
end

rule "Regla de obtencion de la contraseña del grupo (telefono)"
 when
 	obGeneral:IdentificarGrupo(group:objectReferenceId, state == Objetivo.REFINED)
 	ob:ObtenerIDGrupo(objectReferenceId == group, state == Objetivo.SOLVED)
 	fc:FocoGrupo(grupo == group)
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.telefono, msgg:mensajeNotificacion )
    gr:Grupo(grupo == group)
 then
 	
 	if (gr.getTelefono().equals(msgg)){
 		obGeneral.setSolving();
 		TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  		tarea.ejecutar(group, conversacion.msg("passCorrecta"));	
 	}
 	else {
 		obGeneral.setPending();
 		ob.setPending();
 		fc.setFoco(ob);
 		TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  		tarea.ejecutar(group, conversacion.msg("passIncorrecta"));
 	}
 	gr.actividad();
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	update(obGeneral);
   	update(ob);
   	update(fc);
   	retract(notif);
end

rule "Regla de solicitud del identificador del grupo"
 when
 	obj:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	fc:FocoGrupo(foco == null, grupo == group)
 	not( exists (ObtenerIDGrupo(objectReferenceId == group)))
 then
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	
  	Objetivo ob = new ObtenerIDGrupo();
	ob.setobjectReferenceId(group);
	fc.setFoco(ob);
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea.ejecutar(group, conversacion.msg("peticionIDGrupo"));	
  
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
    insert(ob);
    update(obj);
    update(fc);
end

rule "Regla de obtencion del identificador del grupo"
 when
 	obGeneral:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerIDGrupo(objectReferenceId == group, state == Objetivo.PENDING)
 	fc:FocoGrupo(grupo == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.idgrupo, msgg:mensajeNotificacion )
    gr:Grupo(grupo == group)
 then
 	ob.setSolved();
 	gr.setId(msgg);
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(ObtenerGrupoDesdePersistencia.class);
    tarea.ejecutar(group,gr,obGeneral);
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	update(ob);
   	update(fc);
   	update(obGeneral);
   	update(gr);
   	retract(notif);
end

rule "Notificar desconocimiento"
 when
 	notif:Notificacion(group:identNotificador, tipoNotificacion == VocabularioGestionQuedadas.ExtraccionSemanticaNull )
 	fc:FocoGrupo(grupo == group)
 	gr:Grupo(grupo == group);
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(NotificarAlGrupoSinContexto.class);
    tarea.ejecutar(fc);
    gr.actividad();
    retract(notif);
    update(fc);
    update(gr);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Finalizar la identificación del grupo"
 when
 	ob:IdentificarGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	ObtenerIDGrupo(objectReferenceId == group , state == Objetivo.SOLVED);
 	ObtenerNumIntegrantes(objectReferenceId == group, state == Objetivo.SOLVED)
 	ObtenerEdad(objectReferenceId == group, state == Objetivo.SOLVED)
 	ObtenerSexo(objectReferenceId == group, state == Objetivo.SOLVED)
 	ObtenerTelefono(objectReferenceId == group, state == Objetivo.SOLVED)
 	gr:Grupo(grupo == group)
 	fc:FocoGrupo(grupo == group)
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(AlmacenarGrupoIdentificado.class);
 	tarea.ejecutar(gr);
 	fc.setFoco(null);
 	
 	TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea2.ejecutar(group, conversacion.msg("persistenciaGrupoCompletada"));	
 	ob.setSolving();
 	
 	update(ob);
 	update(fc);
end

rule "Notificar a agentes de la finalización de la identificación del grupo"
 when 
 	obj:IdentificarGrupo(group:objectReferenceId, state == Objetivo.SOLVING)
    gr:Grupo(grupo == group)
 then
 	Tarea tarea = gestorTareas.crearTarea(NotificarGrupoIdentificado.class);
    tarea.ejecutar(group, gr);
    obj.setSolved();
	update(obj);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Redireccionar mensaje a agente quedadas"
 when
    IdentificarGrupo(group:objectReferenceId, state == Objetivo.SOLVED)
    notif:Notificacion(identNotificador == group, tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    gr:Grupo(grupo == group)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	gr.actividad();
  	Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoQuedadas);
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract(notif);
end

rule "Contexto incorrecto Luego de identificar"
 when 
   notif:Notificacion(identInterlc:identNotificador, 
    		tipoNotificacion != tipoNotifPaciente.inicioPeticion &&
    		tipoNotificacion != tipoNotifPaciente.consulta && 
    		tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    //obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc, foco == null)
    cu:UsuarioContexto(usuario == identInterlc)
 then
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea.ejecutar(identInterlc, cu.getNombre()+ ", " + conversacion.msg("distribucion"));	
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
  	retract(notif);
end

rule "Recibir Objetivo primera vez"
 when 
 	notif:NotificacionObjetivo(identInterlc:identNotificador, tipoNotificacion == tipoNotif.objetivo, agente == "INIT")
 	//obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
 	obj:IdentificarUsuario(state == Objetivo.SOLVED ,objectReferenceId == identInterlc )
    fc:FocoUsuario(usuario == identInterlc, foco == null)
    cu:UsuarioContexto(usuario == identInterlc)
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea.ejecutar(identInterlc, cu.getNombre()+ ", " + conversacion.msg("distribucion"));	
 	cu.actividad();
	fc.refocus();
	update(fc);
	update(cu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
 	retract(notif);
end
/*
rule "Focalizacion de distribucion de mensajes"
 when
    obj:IdentificarUsuario(state == Objetivo.SOLVED ,user:objectReferenceId)
    cu:UsuarioContexto(usuario == user)
    fc:FocoUsuario(usuario == user)
 then
	obj.setSolving();
	Objetivo dm = new DistribuirMensajes();
	dm.setobjectReferenceId(user);
	fc.setFoco(dm);
	dm.setSolving();

  TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea.ejecutar(user, cu.getNombre()+ ", " + conversacion.msg("distribucion"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   update(obj);
   	insert(dm);
	update(fc);
end
*/

rule "Solicita Distribucion de mensajes paciente"
 when
    notif:Notificacion(identInterlc:identNotificador, 
    		(tipoNotificacion == tipoNotifPaciente.inicioPeticion ||
    		tipoNotificacion == tipoNotifPaciente.consulta) && 
    		tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    //obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc)
    cu:UsuarioContexto(usuario == identInterlc)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	cu.actividad();
    Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(identInterlc, notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoPaciente);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
    retract(notif);
end

rule "Distribucion de mensajes paciente"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    obj:DistribuirMensajesPaciente(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc, foco == obj)
    cu:UsuarioContexto(usuario == identInterlc)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	cu.actividad();
  	Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(identInterlc, notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoPaciente);
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract(notif);
end

rule "Recibir Objetivo Paciente"
 when 
 	notif:NotificacionObjetivo(identInterlc:identNotificador, agente == "PACIENTE")
 	//obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc)
    cu:UsuarioContexto(usuario == identInterlc)
 then
	Objetivo dp = new DistribuirMensajesPaciente();	
	dp.setobjectReferenceId(identInterlc);
	cu.actividad();
	fc.setFoco(dp);
	insert(dp);
	update(fc);
	update(cu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
 	retract(notif);
end


rule "Solicita Distribucion de mensajes medico"
 when
    notif:Notificacion(identInterlc:identNotificador, 
    		tipoNotificacion == tipoNotifMedico.inicioAnulacion && 
    		tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    //obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc)
    cu:UsuarioContexto(usuario == identInterlc)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	cu.actividad();
    Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(identInterlc, notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoMedico);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
    retract(notif);
end

rule "Distribucion de mensajes medico"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    obj:DistribuirMensajesMedico(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc, foco == obj)
    cu:UsuarioContexto(usuario == identInterlc)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	cu.actividad();
  	Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(identInterlc, notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoMedico);
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract(notif);
end

rule "Recibir Objetivo Medico"
 when 
 	notif:NotificacionObjetivo(identInterlc:identNotificador, agente == "MEDICO")
 	//obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc)
    cu:UsuarioContexto(usuario == identInterlc)
 then
	Objetivo dp = new DistribuirMensajesMedico();	
	dp.setobjectReferenceId(identInterlc);
	cu.actividad();
	fc.setFoco(dp);
	insert(dp);
	update(fc);
	update(cu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
 	retract(notif);
end

rule "Recibir Objetivo Completado"
 when 
 	notif:NotificacionObjetivo(identInterlc:identNotificador, tipoNotificacion == tipoNotif.objetivo, agente == "RESET")
 	//obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc, foco != null)
    cu:UsuarioContexto(usuario == identInterlc)
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea.ejecutar(identInterlc, conversacion.msg("objetivoLogrado"));	
 	cu.actividad();
	fc.refocus();
	update(fc);
	update(cu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
 	retract(notif);
end



rule "Detectar Inactividad"
	when 
	 cu:UsuarioContexto(user:usuario, inactividad(1) );
	 not( exists Inactividad(user == objectReferenceId ))
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	Objetivo obb = new Inactividad();
	obb.setobjectReferenceId(user);
	insert( obb );
	cu.actividad();
  TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	if( cu.getNombre() == null){
  		tarea.ejecutar(cu.getUsuario(), conversacion.msg("inactividad"));
  	}else{
  		tarea.ejecutar(cu.getUsuario(), cu.getNombre() +", "+ conversacion.msg("inactividad"));
  	}
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Detectar Inactividad prolongada"
	when 
 	 cu:UsuarioContexto(user:usuario, inactividad(2) );
	 Inactividad(user == objectReferenceId, state == Objetivo.PENDING )
	 
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(EliminarSessionUsuario.class);
     tarea2.ejecutar(cu.usuario);
  TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea.ejecutar(user,  conversacion.msg("despedida"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract( cu );
end

rule "Despedirse"
	when 
	 notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.despedida)
 	 gr:Grupo(grupo == identInterlc )
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
   Tarea tarea = gestorTareas.crearTarea(EliminarSesionGrupo.class);
     tarea.ejecutar(gr.grupo);
   TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea2.ejecutar(gr.grupo,  conversacion.msg("despedida"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   
   retract( notif );
end

rule "fechaAnterior"
	when 
	 notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.fechaAnterior)
	 cu:UsuarioContexto(usuario == identInterlc )
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
   TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea2.ejecutar(cu.usuario,  conversacion.msg("fechaAnterior"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract( notif );
end


rule "Timer Inactividad"
	timer ( int: 1m )
	when 
	 m:UsuarioContexto()
	 then
   update(m);
end
	

